<ns0:test-suite xmlns:ns0="urn:model.allure.qatools.yandex.ru" start="1545639713172" stop="1545639713238">
  <name>test_login</name>
  <labels/>
  <test-cases>
    <test-case start="1545639713172" status="passed" stop="1545639713182">
      <name>TestLogin.test_a</name>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="2488-MainThread"/>
        <label name="host" value="2"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1545639713184" status="failed" stop="1545639713238">
      <name>TestLogin.test_b</name>
      <failure>
        <message>AssertionError: assert 0</message>
        <stack-trace>self = &lt;test_login.TestLogin object at 0x0000000004541320&gt;

    @allure.step("测试登录的步骤")
    def test_b(self):
        print("\n222")
        allure.attach("描述1","请输入用户名")
        print("\n3333")
        allure.attach("描述2", "请输入密码")
&gt;       assert 0
E       assert 0

script\test_login.py:13: AssertionError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="2488-MainThread"/>
        <label name="host" value="2"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps>
        <step start="1545639713184" status="failed" stop="1545639713188">
          <name>测试登录的步骤</name>
          <title>测试登录的步骤</title>
          <attachments>
            <attachment source="29376c47-44e3-48bb-80e4-f281a0267f33-attachment.txt" title="描述1" type="text/plain"/>
            <attachment source="e267cfcd-0fe3-448c-867d-7917a1257627-attachment.txt" title="描述2" type="text/plain"/>
          </attachments>
          <steps/>
        </step>
      </steps>
    </test-case>
  </test-cases>
</ns0:test-suite>
